# Generated by Django 2.1 on 2020-07-31 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ANovelDataText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'anovel_text',
            },
        ),
        migrations.CreateModel(
            name='ANovelModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('antime', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spiders.ANovelDataText')),
            ],
            options={
                'db_table': 'anovel',
            },
        ),
        migrations.CreateModel(
            name='MeiZiTu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tutime', models.CharField(max_length=30)),
                ('imgname', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='NewsDataModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('newstime', models.CharField(max_length=30)),
                ('newurl', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewsDataText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'news_text',
            },
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('playtime', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.AddField(
            model_name='newsdatamodel',
            name='detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spiders.NewsDataText'),
        ),
    ]
